"""slife info fixed

Revision ID: 0ddd9d102b30
Revises: 6de9bed9119f
Create Date: 2023-12-09 15:43:25.569520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ddd9d102b30'
down_revision = '6de9bed9119f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lifeinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('life_info_holder', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'character', ['life_info_holder'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lifeinfo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('life_info_holder')

    # ### end Alembic commands ###
