"""char add to users table

Revision ID: 1593bb8eca6d
Revises: e55713501ec7
Create Date: 2023-11-15 15:09:44.936918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1593bb8eca6d'
down_revision = 'e55713501ec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_character'), ['character'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_character'))
        batch_op.drop_column('character')

    # ### end Alembic commands ###
