"""children_folders

Revision ID: 2908105b83a5
Revises: 18365b7faebd
Create Date: 2024-01-06 16:24:19.312277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2908105b83a5'
down_revision = '18365b7faebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('folder_to_folder_table')
    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_root', sa.Boolean(), nullable=True))
        batch_op.drop_index('ix_folder_name')
        batch_op.create_index(batch_op.f('ix_folder_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_folder_name'))
        batch_op.create_index('ix_folder_name', ['name'], unique=False)
        batch_op.drop_column('is_root')

    op.create_table('folder_to_folder_table',
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('folder_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], name='folder_to_folder_table_file_id_fkey'),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], name='folder_to_folder_table_folder_id_fkey'),
    sa.PrimaryKeyConstraint('file_id', 'folder_id', name='folder_to_folder_table_pkey')
    )
    # ### end Alembic commands ###
