"""removed commas at end

Revision ID: 2eb22be9269b
Revises: 67d7653c6cac
Create Date: 2023-11-29 10:48:13.674186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eb22be9269b'
down_revision = '67d7653c6cac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('char_cls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cls_5e_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'cls_5e', ['cls_5e_id'], ['id'])
        batch_op.create_foreign_key(None, 'character', ['character_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('char_cls', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cls_5e_id')
        batch_op.drop_column('character_id')

    # ### end Alembic commands ###
