"""char_know no id or name

Revision ID: 3083ee516af5
Revises: 8c242f220634
Create Date: 2023-12-10 07:59:21.115231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3083ee516af5'
down_revision = '8c242f220634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('char_know', schema=None) as batch_op:
        batch_op.alter_column('learner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index('ix_char_know_char_char')
        batch_op.drop_column('char_char')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('char_know', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('char_char', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.create_index('ix_char_know_char_char', ['char_char'], unique=False)
        batch_op.alter_column('subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('learner_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
