"""cls_info_updated

Revision ID: 3d9074ce022e
Revises: ee6d7cc6d132
Create Date: 2023-12-07 15:07:49.975896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9074ce022e'
down_revision = 'ee6d7cc6d132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clsinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('char_cls_info_name', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_clsinfo_char_name')
        batch_op.create_index(batch_op.f('ix_clsinfo_char_cls_info_name'), ['char_cls_info_name'], unique=True)
        batch_op.drop_column('char_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clsinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('char_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_clsinfo_char_cls_info_name'))
        batch_op.create_index('ix_clsinfo_char_name', ['char_name'], unique=False)
        batch_op.drop_column('char_cls_info_name')

    # ### end Alembic commands ###
