"""added summary

Revision ID: 43affe3e0526
Revises: c42ec757470b
Create Date: 2024-05-17 09:07:46.224711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43affe3e0526'
down_revision = 'c42ec757470b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=5000), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.String(length=2000), nullable=True))

    with op.batch_alter_table('alignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=2000), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=5000),
               existing_nullable=True)

    with op.batch_alter_table('ammo_power', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=2000), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=5000),
               existing_nullable=True)

    with op.batch_alter_table('architype', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=2000), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=5000),
               existing_nullable=True)

    with op.batch_alter_table('armor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=5000), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.String(length=2000), nullable=True))

    with op.batch_alter_table('background', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=2000), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=5000),
               existing_nullable=True)

    with op.batch_alter_table('cls_5e', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=5000), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.String(length=2000), nullable=True))

    with op.batch_alter_table('cybernetic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=2000), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=5000),
               existing_nullable=True)

    with op.batch_alter_table('damagetype', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=5000), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.String(length=2000), nullable=True))

    with op.batch_alter_table('dice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=5000), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.String(length=2000), nullable=True))

    with op.batch_alter_table('faction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=2000), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=5000),
               existing_nullable=True)

    with op.batch_alter_table('feat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=2000), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=5000),
               existing_nullable=True)

    with op.batch_alter_table('feature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=2000), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=5000),
               existing_nullable=True)

    with op.batch_alter_table('gear', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=2000), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=5000),
               existing_nullable=True)

    with op.batch_alter_table('ladder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=2000), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=5000),
               existing_nullable=True)

    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=5000), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.String(length=2000), nullable=True))

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=2000), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=5000),
               existing_nullable=True)

    with op.batch_alter_table('mech', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=2000), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=5000),
               existing_nullable=True)

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=2000), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=5000),
               existing_nullable=True)

    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=2000), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=5000),
               existing_nullable=True)

    with op.batch_alter_table('rank', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=2000), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=5000),
               existing_nullable=True)

    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=5000), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.String(length=2000), nullable=True))

    with op.batch_alter_table('spell', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=2000), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=5000),
               existing_nullable=True)

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=2000), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=5000),
               existing_nullable=True)

    with op.batch_alter_table('weapon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=2000), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=5000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weapon', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.drop_column('summary')

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.drop_column('summary')

    with op.batch_alter_table('spell', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.drop_column('summary')

    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.drop_column('summary')
        batch_op.drop_column('description')

    with op.batch_alter_table('rank', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.drop_column('summary')

    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.drop_column('summary')

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.drop_column('summary')

    with op.batch_alter_table('mech', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.drop_column('summary')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.drop_column('summary')

    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.drop_column('summary')
        batch_op.drop_column('description')

    with op.batch_alter_table('ladder', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.drop_column('summary')

    with op.batch_alter_table('gear', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.drop_column('summary')

    with op.batch_alter_table('feature', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.drop_column('summary')

    with op.batch_alter_table('feat', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.drop_column('summary')

    with op.batch_alter_table('faction', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.drop_column('summary')

    with op.batch_alter_table('dice', schema=None) as batch_op:
        batch_op.drop_column('summary')
        batch_op.drop_column('description')

    with op.batch_alter_table('damagetype', schema=None) as batch_op:
        batch_op.drop_column('summary')
        batch_op.drop_column('description')

    with op.batch_alter_table('cybernetic', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.drop_column('summary')

    with op.batch_alter_table('cls_5e', schema=None) as batch_op:
        batch_op.drop_column('summary')
        batch_op.drop_column('description')

    with op.batch_alter_table('background', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.drop_column('summary')

    with op.batch_alter_table('armor', schema=None) as batch_op:
        batch_op.drop_column('summary')
        batch_op.drop_column('description')

    with op.batch_alter_table('architype', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.drop_column('summary')

    with op.batch_alter_table('ammo_power', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.drop_column('summary')

    with op.batch_alter_table('alignment', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.drop_column('summary')

    with op.batch_alter_table('ability', schema=None) as batch_op:
        batch_op.drop_column('summary')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
