"""new direction

Revision ID: 4518a5d86568
Revises: 6b01e24fbde7
Create Date: 2023-12-09 15:22:54.542697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4518a5d86568'
down_revision = '6b01e24fbde7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('char_cls_arch_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('char_cls_arch_table',
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cls_5e_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('architype_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['architype_id'], ['architype.id'], name='char_cls_arch_table_architype_id_fkey'),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='char_cls_arch_table_character_id_fkey'),
    sa.ForeignKeyConstraint(['cls_5e_id'], ['cls_5e.id'], name='char_cls_arch_table_cls_5e_id_fkey'),
    sa.PrimaryKeyConstraint('character_id', 'cls_5e_id', 'architype_id', name='char_cls_arch_table_pkey')
    )
    # ### end Alembic commands ###
