"""made char_info one to one

Revision ID: 51b12944603b
Revises: a4cfd73ff0a9
Create Date: 2023-12-02 15:49:28.762890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b12944603b'
down_revision = 'a4cfd73ff0a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('char_info_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('char_info_table',
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('info_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='char_info_table_character_id_fkey'),
    sa.ForeignKeyConstraint(['info_id'], ['info.id'], name='char_info_table_info_id_fkey'),
    sa.PrimaryKeyConstraint('character_id', 'info_id', name='char_info_table_pkey')
    )
    # ### end Alembic commands ###
