"""CharCls object added

Revision ID: 67d7653c6cac
Revises: 
Create Date: 2023-11-29 09:42:12.128457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d7653c6cac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('char_cls_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('char_cls_table',
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cls_5e_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='char_cls_table_character_id_fkey'),
    sa.ForeignKeyConstraint(['cls_5e_id'], ['cls_5e.id'], name='char_cls_table_cls_5e_id_fkey'),
    sa.PrimaryKeyConstraint('character_id', 'cls_5e_id', name='char_cls_table_pkey')
    )
    # ### end Alembic commands ###
