"""char table changed

Revision ID: 733e8e82ddbf
Revises: ec3027fc1ad2
Create Date: 2023-12-22 11:00:46.638555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733e8e82ddbf'
down_revision = 'ec3027fc1ad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_desc', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('pure', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('char_sum', sa.String(length=5000), nullable=True))
        batch_op.alter_column('job',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=10),
               existing_nullable=True)

    with op.batch_alter_table('lifeinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_lifeinfo_char_name')
        batch_op.create_index(batch_op.f('ix_lifeinfo_name'), ['name'], unique=True)
        batch_op.drop_column('char_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lifeinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('char_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_lifeinfo_name'))
        batch_op.create_index('ix_lifeinfo_char_name', ['char_name'], unique=False)
        batch_op.drop_column('name')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('job',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.drop_column('char_sum')
        batch_op.drop_column('pure')
        batch_op.drop_column('job_desc')

    # ### end Alembic commands ###
