"""added skill ability relationship

Revision ID: 74c7d0b4ea31
Revises: c22d90b47405
Create Date: 2024-01-03 09:21:34.091789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c7d0b4ea31'
down_revision = 'c22d90b47405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ability', sa.String(length=64), nullable=True))
        batch_op.create_foreign_key(None, 'ability', ['ability'], ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ability')

    # ### end Alembic commands ###
