"""property table added

Revision ID: 7cb2f4f968ea
Revises: 67fd2e3b6269
Create Date: 2023-12-05 12:04:02.397632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb2f4f968ea'
down_revision = '67fd2e3b6269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('architype', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('architype', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
