"""char_know reverted back

Revision ID: 8c242f220634
Revises: 5675e6ebd59a
Create Date: 2023-12-09 16:16:36.802746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c242f220634'
down_revision = '5675e6ebd59a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('char_know', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('char_char', sa.String(length=64), nullable=True))
        batch_op.alter_column('learner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_char_know_char_char'), ['char_char'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('char_know', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_char_know_char_char'))
        batch_op.alter_column('subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('learner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('char_char')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
