"""life info table updated

Revision ID: 90cb7e9f2883
Revises: ad0e95943c21
Create Date: 2023-12-04 11:38:52.137830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90cb7e9f2883'
down_revision = 'ad0e95943c21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.drop_index('ix_info_char_name')

    op.drop_table('info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('char_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('birth_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('real_age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('public_history', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('learned_history', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('hidden_history', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='info_pkey')
    )
    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.create_index('ix_info_char_name', ['char_name'], unique=False)

    # ### end Alembic commands ###
