"""abilityscores fixing

Revision ID: a4b9e1b029e4
Revises: 4518a5d86568
Create Date: 2023-12-09 15:38:52.267356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4b9e1b029e4'
down_revision = '4518a5d86568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ability_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('able_char', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'character', ['able_char'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ability_scores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('able_char')

    # ### end Alembic commands ###
