"""skillscores table added

Revision ID: a4cfd73ff0a9
Revises: c02fd62a078e
Create Date: 2023-12-02 15:47:48.002960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4cfd73ff0a9'
down_revision = 'c02fd62a078e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proficiency', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('speed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('passive_perc', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('armor_class', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('inspiration', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('initiative', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cur_hit_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('temp_hit_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('backpack', sa.String(length=5000), nullable=True))
        batch_op.add_column(sa.Column('play_notes', sa.String(length=5000), nullable=True))

    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('history', sa.String(length=5000), nullable=True))
        batch_op.add_column(sa.Column('hid_history', sa.String(length=5000), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('admin')

    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.drop_column('hid_history')
        batch_op.drop_column('history')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('play_notes')
        batch_op.drop_column('backpack')
        batch_op.drop_column('temp_hit_points')
        batch_op.drop_column('cur_hit_points')
        batch_op.drop_column('initiative')
        batch_op.drop_column('inspiration')
        batch_op.drop_column('armor_class')
        batch_op.drop_column('passive_perc')
        batch_op.drop_column('speed')
        batch_op.drop_column('proficiency')

    # ### end Alembic commands ###
