"""char_know pick_subject added

Revision ID: ace9c1313b13
Revises: 3083ee516af5
Create Date: 2023-12-11 12:59:46.605193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace9c1313b13'
down_revision = '3083ee516af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('spliced', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('robot', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('robot')
        batch_op.drop_column('spliced')
        batch_op.drop_column('job')

    # ### end Alembic commands ###
