"""weapon and dice tables added

Revision ID: ad0e95943c21
Revises: 51b12944603b
Create Date: 2023-12-04 10:41:54.430466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad0e95943c21'
down_revision = '51b12944603b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_history', sa.String(length=5000), nullable=True))
        batch_op.add_column(sa.Column('learned_history', sa.String(length=5000), nullable=True))
        batch_op.add_column(sa.Column('hidden_history', sa.String(length=5000), nullable=True))
        batch_op.drop_column('hid_history')
        batch_op.drop_column('history')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('history', sa.VARCHAR(length=5000), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hid_history', sa.VARCHAR(length=5000), autoincrement=False, nullable=True))
        batch_op.drop_column('hidden_history')
        batch_op.drop_column('learned_history')
        batch_op.drop_column('public_history')

    # ### end Alembic commands ###
