"""class picker readded

Revision ID: bead5644c0dd
Revises: 2eb22be9269b
Create Date: 2023-11-30 11:28:55.415654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bead5644c0dd'
down_revision = '2eb22be9269b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cls_5e', schema=None) as batch_op:
        batch_op.drop_column('cls_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cls_5e', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cls_level', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
