"""updated File table

Revision ID: c42ec757470b
Revises: fe49173e3f63
Create Date: 2024-03-31 17:09:04.506978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c42ec757470b'
down_revision = 'fe49173e3f63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('repr_path', sa.String(length=10000), nullable=True))
        batch_op.add_column(sa.Column('access_path', sa.String(length=10000), nullable=True))
        batch_op.drop_index('ix_file_path')
        batch_op.create_index(batch_op.f('ix_file_access_path'), ['access_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_author'), ['author'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_repr_path'), ['repr_path'], unique=False)
        batch_op.drop_column('path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.VARCHAR(length=10000), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_file_repr_path'))
        batch_op.drop_index(batch_op.f('ix_file_author'))
        batch_op.drop_index(batch_op.f('ix_file_access_path'))
        batch_op.create_index('ix_file_path', ['path'], unique=False)
        batch_op.drop_column('access_path')
        batch_op.drop_column('repr_path')
        batch_op.drop_column('author')

    # ### end Alembic commands ###
