"""adders added to most tables

Revision ID: d2e64688ceb1
Revises: ace9c1313b13
Create Date: 2023-12-12 15:22:31.742511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e64688ceb1'
down_revision = 'ace9c1313b13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weapon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weapon', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
